###
POST http://localhost:8080/api/sock
Content-Type: application/json

{
  "color": "BLACK",
  "size": "SIZE_37",
  "cottonPart": 50,
  "quantity": 10
}
###
POST http://localhost:8080/api/sock
Content-Type: application/json

{
  "color": "RED",
  "size": "SIZE_37",
  "cottonPart": 50,
  "quantity": 10
}
###
POST http://localhost:8080/api/sock
Content-Type: application/json

{
  "color": "YELLOW",
  "size": "SIZE_37",
  "cottonPart": 0,
  "quantity": 20
}

###
PUT http://localhost:8080/api/sock
Content-Type: application/json

{
  "color": "RED",
  "size": "SIZE_37",
  "cottonPart": 50,
  "quantity": 25
}

###
PUT http://localhost:8080/api/sock
Content-Type: application/json

{
  "color": "BLACK",
  "size": "SIZE_37",
  "cottonPart": -10,
  "quantity": 25
}

###
GET http://localhost:8080/api/sock
###
GET http://localhost:8080/api/sock?color=BLACK
###
GET http://localhost:8080/api/sock?cottonMin=60
###
GET http://localhost:8080/api/sock?cottonMin=90&color=RED