###
POST http://localhost:8080/api/sock
Content-Type: application/json

{
  "color": "BLACK",
  "size": 37,
  "cottonPart": 50,
  "quantity": 10
}
###
POST http://localhost:8080/api/sock
Content-Type: application/json

{
  "color": "RED",
  "size": 37,
  "cottonPart": 90,
  "quantity": 100
}
###
POST http://localhost:8080/api/sock
Content-Type: application/json

{
  "color": "YELLOW",
  "size": 37,
  "cottonPart": 0,
  "quantity": 200
}

###
PUT http://localhost:8080/api/sock
Content-Type: application/json

{
  "color": "RED",
  "size": 37,
  "cottonPart": 50,
  "quantity": 25
}

###
PUT http://localhost:8080/api/sock
Content-Type: application/json

{
  "color": "BLACK",
  "size": 37,
  "cottonPart": -10,
  "quantity": 25
}

### не рабочий !!!
POST http://localhost:8080/api/sock?color=RED&size=37&cottonPart=40&quantity=5
### не рабочий !!!
PUT http://localhost:8080/api/sock?COLOR=RED&size=37&cottonPart=40&quantity=5

### нужно реализовать
GET http://localhost:8080/api/sock?color=YELLOW&SIZE=37&cottonMin=0
### нужно реализовать
GET http://localhost:8080/api/sock?color=BLACK&size=37


### рабочий все носки
GET http://localhost:8080/api/sock
### рабочий все черные носки
GET http://localhost:8080/api/sock?color=BLACK
### рабочий
GET http://localhost:8080/api/sock?cottonMin=100
### рабочий
GET http://localhost:8080/api/sock?cottonMin=90&color=RED

